cache: bundler
sudo: false
language: ruby

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

matrix:
  include:
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord_4_2.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/activerecord_5_0.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/activerecord_5_1.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/activerecord_5_2.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/activerecord_6_0.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/activerecord_6_1.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/activerecord_master.gemfile

before_install:
  - gem update --system
  - gem install bundler -v "2.2.9" # Bundler 2.2.10 is broken, see https://github.com/rubygems/rubygems/issues/4380
